name: CI

on:
  pull_request:
    paths: '/task/blob/main/.github/workflows/blank.yml'
    types: [opened]
    branches:
      - challenge
      
jobs:
  getflag:
    runs-on:
      labels: self-hosted

    steps:
      - name: Run Python script to generate flag value
        run: |
          python3 /home/pidor/task/drop_flag_url.py
        id: python_script

